# Use postgres/example user/password credentials
version: '3.1'
 
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: henrique
      POSTGRES_USER: henrique
      POSTGRES_DB: ngcash
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5444:5432
  app:
    container_name: server
    restart: always
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    container_name: client
    restart: always
    build: ./client
    ports:
      - 5173:5173
    depends_on:
      - app