# Use postgres/example user/password credentials
version: '3.1'
 
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: henrique
      POSTGRES_USER: henrique
      POSTGRES_DB: ngcash
    ports:
      - 5441:5432
  app:
    container-name: api
    restart: always
    build: ./server
    ports:
      -"3030:3030"
    depends_on:
      - db
  front:
    container_name: client
    restart: always
    build: ./client
    ports:
      -"5173:5173"
    depends_on:
      - app