# Use postgres/example user/password credentials
version: '3.1'
 
services:
 
 db:
   image: postgres:latest
   restart: always
   environment:
     POSTGRES_PASSWORD: henrique
     POSTGRES_USER: henrique
     POSTGRES_DB: ngcash
   ports:
     - 5441:5432